### ISSUE TITLE
java 3

### ISSUE THREAD

**Issue by joserome** [joserome/lenguajes-joserome#5]
@daton profesor una pregunta por que me sale este error cuando
 estoy agregando el tomcat a los servers?
que significa o que debo hacer para quitarlo?

**Comment by daton** [comment]
Cual error te sale?

**Comment by joserome** [comment]
jun 30, 2015 11:21:14 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFORMACIÓN: Desplieque del descriptor de configuración F:\tomcat\conf\Catalina\localhost\springmaven.xml
jun 30, 2015 11:21:14 PM org.apache.catalina.startup.HostConfig deployDescriptor
GRAVE: Error durante el despliegue del descriptor de configuración F:\tomcat\conf\Catalina\localhost\springmaven.xml
java.io.IOException: El dispositivo no está listo
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
    at java.io.File.getCanonicalPath(File.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1635)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by joserome** [comment]
@daton 

jun 30, 2015 11:21:14 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFORMACIÓN: Desplieque del descriptor de configuración F:\tomcat\conf\Catalina\localhost\springmaven.xml
jun 30, 2015 11:21:14 PM org.apache.catalina.startup.HostConfig deployDescriptor
GRAVE: Error durante el despliegue del descriptor de configuración F:\tomcat\conf\Catalina\localhost\springmaven.xml
java.io.IOException: El dispositivo no está listo
at java.io.WinNTFileSystem.canonicalize0(Native Method)
at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
at java.io.File.getCanonicalPath(File.java:618)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1635)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by daton** [comment]
ese error tiene que ver en que tu proyecto primero lo tenias en tu memoria y estaba en la unidad F:, luego a lo mejor lo copiaste en otra unidad o la memoria ya no estaba en F: y estaba en otro puerto USB

**Comment by joserome** [comment]
y como lo quito?
es que nisiquiera abri el proyecto, solamente cargue el servidor tomcat y me marco ese error
entonces por eso se me hace raro

**Comment by daton** [comment]
pon tu proyecto en la unidad c: no lo tengas en la memoria, y ya en netbeans le ponces clean and build a tu proyecto

**Comment by joserome** [comment]
bueno deje ver si si se quita ese error

**Comment by daton** [comment]
va que va

**Comment by joserome** [comment]
profesor ya ayer ya se me paso avisarle por que note que mi wampserver no estaba dando
y pense que eso era lo que marcaba el error
pero cuando lo arregle siguio igual cree que pueda verlo en la tarde para que me ayude ver que es porfavor    y tambien para unas dudas que tengo

**Comment by daton** [comment]
si jose ñlui9s me buscas a las 6 pm :rabbit:

**Comment by joserome** [comment]
vale

**Comment by daton** [comment]
:beers:

**Comment by daton** [comment]
Si se resolvio el problema?

**Comment by joserome** [comment]
Si ya cuando lo corrió ya pudo acceder a las 2 paginas
Una pregunta mañana a que hora llega a laescuela es que no se muy bien hacer lo de hibernate

**Comment by daton** [comment]
llego como a las 7:30 me buscas a esa hora

**Comment by joserome** [comment]
bueno pero seguro profe jaja

**Comment by daton** [comment]
jejejeje si :)

**Comment by joserome** [comment]
profesor el dia de hoy tiene alguna clase
para ver si lo espero y si me puede resolver la duda de hibernate

**Comment by daton** [comment]
HOla Jose, mañana buscame a las 7 pm antes del examen para ver tu duda va?

**Comment by joserome** [comment]
profesor podria subir ahorita mi proyecto y que me revise rapido por que no me hace la inserccion de datos en la tabla por favor

igual como se sube el proyecto es que ya no recuerdo je

**Comment by daton** [comment]
Si Jose, subelo y te lo reviso ahorita

**Comment by joserome** [comment]
pero como se sube el proyecto
es que cuando le doy click derecho a mi proyecto no me da la opcion de git

**Comment by daton** [comment]
Tienes que darle primero en la opcion Versioning

**Comment by joserome** [comment]
profe ya puse eso de versioning pero aun asi no lo puedo subir 
primero debo clonar el repositorio o como?

**Comment by daton** [comment]
una vez hecho eso creas un repositorio vacio en github y ya despues le 
haces el pull sobre tu proyecto,  ya despues el push peroprimero el pull 
en el pull asegurate de poner la url de tu nuevo repositorio y listo

**Comment by joserome** [comment]
ya ya esta
este en un repositorio que se llama java 3 haber si lo puede checar porfavor

**Comment by daton** [comment]
:D

**Comment by joserome** [comment]
Bueno lo veo a las 7 vale
